name: CICD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20         

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (optional)
        run: npm test

      - name: Build Project (for React/Vite)
        run: npm run build

      - name: Deploy using SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVETE_KEY }}
          source: "./dist/"
          target: "/var/www/html/somesh/office_web"
